import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { bridge } from './bridge.mjs';
const root = await mkdtemp(path.join(tmpdir(), 'opentax-editor-'));
try {
  const content = path.join(root, 'content/articles');
  const stage = path.join(root, 'drafts');
  await mkdir(content, { recursive: true });
  const original = [{ slug: 'freee-cost-review', status: 'draft', title: '元', description: '説明', summary: '要約', updatedAt: '2026-10-02', publicationApproval: 'pending', sources: [{ verified: true }] }, { slug: 'other', status: 'draft', title: '保持' }];
  const manifestPath = path.join(content, 'manifest.json');
  const bodyPath = path.join(content, 'freee-cost-review.md');
  await writeFile(manifestPath, JSON.stringify(original));
  await writeFile(bodyPath, '## 元\n\n本文\n');
  await bridge('import', root, stage);
  const draftPath = path.join(stage, 'freee-cost-review.json');
  const draft = JSON.parse(await readFile(draftPath, 'utf8'));
  draft.title = '改訂'; draft.markdown = '## 改訂\n\n|列|値|\n|---|---|\n|a|b|\n\n{{pricing:freee-starter-monthly:amountInclTaxDisplay}}\n';
  await writeFile(draftPath, JSON.stringify(draft));
  await bridge('apply', root, stage);
  const actual = JSON.parse(await readFile(manifestPath, 'utf8'));
  assert.equal(await readFile(bodyPath, 'utf8'), draft.markdown);
  assert.deepEqual(actual[1], original[1]);
  assert.equal(actual[0].status, 'draft'); assert.equal(actual[0].publicationApproval, 'pending');
  assert.deepEqual(actual[0].sources, original[0].sources);
  await writeFile(bodyPath, '別の編集');
  await assert.rejects(() => bridge('apply', root, stage), /Source changed/);
  console.log('PASS: Markdown round trip, metadata isolation, draft preservation, conflict detection');
} finally { await rm(root, { recursive: true, force: true }); }
