// テスト用モックデータ
// test@example.com でログインしたときにネットワーク不要で動作するためのハードコーディングデータ

import { Timestamp } from 'firebase/firestore';
import type {
  JournalEntry,
  Document,
  ProfitAndLoss,
  BalanceSheet,
  MonthlySummary,
} from '@/types';

function ts(dateStr: string): Timestamp {
  return Timestamp.fromDate(new Date(dateStr));
}

// ============================================================
// 仕訳データ（FY2025 全月 + FY2026 1〜3月）
// ============================================================
export const MOCK_JOURNALS: JournalEntry[] = [
  // ── FY2025 1月 ──────────────────────────────────────────
  {
    id: 'j001',
    entryNumber: 1,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-01-15'),
    fiscalYear: 2025,
    fiscalMonth: 1,
    debitAccount: 'COMMUNICATION',
    debitAmount: 8800,
    creditAccount: 'BANK',
    creditAmount: 8800,
    counterparty: 'NTTドコモ',
    description: 'NTTドコモ 1月分携帯電話料金',
    taxType: 'standard10',
    taxAmount: 800,
    taxIncluded: true,
    isQualifiedInvoice: true,
    invoiceRegistrationNumber: 'T1234567890123',
    sourceType: 'bank',
    status: 'confirmed',
    createdAt: ts('2025-01-20'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-01-20'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j002',
    entryNumber: 2,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-01-20'),
    fiscalYear: 2025,
    fiscalMonth: 1,
    debitAccount: 'ADVERTISING',
    debitAmount: 15400,
    creditAccount: 'BANK',
    creditAmount: 15400,
    counterparty: 'さくらインターネット',
    description: 'さくらインターネット サーバーレンタル年間契約',
    taxType: 'standard10',
    taxAmount: 1400,
    taxIncluded: true,
    isQualifiedInvoice: true,
    invoiceRegistrationNumber: 'T9876543210987',
    sourceType: 'credit_card',
    status: 'confirmed',
    createdAt: ts('2025-01-25'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-01-25'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 2月 ──────────────────────────────────────────
  {
    id: 'j003',
    entryNumber: 3,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-02-05'),
    fiscalYear: 2025,
    fiscalMonth: 2,
    debitAccount: 'FIXED_ASSETS',
    debitAmount: 165000,
    creditAccount: 'BANK',
    creditAmount: 165000,
    counterparty: 'Apple Japan',
    description: 'MacBook Air M3 業務用PC購入',
    taxType: 'standard10',
    taxAmount: 15000,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'confirmed',
    createdAt: ts('2025-02-10'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-02-10'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j004',
    entryNumber: 4,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-02-15'),
    fiscalYear: 2025,
    fiscalMonth: 2,
    debitAccount: 'SUPPLIES',
    debitAmount: 16500,
    creditAccount: 'BANK',
    creditAmount: 16500,
    counterparty: 'Adobe',
    description: 'Adobe Creative Cloud 年間プラン',
    taxType: 'standard10',
    taxAmount: 1500,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'confirmed',
    createdAt: ts('2025-02-20'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-02-20'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 3月 ──────────────────────────────────────────
  {
    id: 'j005',
    entryNumber: 5,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-03-20'),
    fiscalYear: 2025,
    fiscalMonth: 3,
    debitAccount: 'BANK',
    debitAmount: 550000,
    creditAccount: 'SALES',
    creditAmount: 550000,
    counterparty: '株式会社テクノロジーズ',
    description: 'Webシステム開発 第1フェーズ 完了報酬',
    taxType: 'standard10',
    taxAmount: 50000,
    taxIncluded: true,
    isQualifiedInvoice: true,
    invoiceRegistrationNumber: 'T1111111111111',
    sourceType: 'invoice',
    status: 'confirmed',
    createdAt: ts('2025-03-25'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-03-25'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j006',
    entryNumber: 6,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-03-28'),
    fiscalYear: 2025,
    fiscalMonth: 3,
    debitAccount: 'SUPPLIES',
    debitAmount: 4800,
    creditAccount: 'BANK',
    creditAmount: 4800,
    counterparty: '丸善書店',
    description: 'TypeScript実践入門 技術書籍購入',
    taxType: 'reduced8',
    taxAmount: 356,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'confirmed',
    createdAt: ts('2025-03-30'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-03-30'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 4月 ──────────────────────────────────────────
  {
    id: 'j007',
    entryNumber: 7,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-04-01'),
    fiscalYear: 2025,
    fiscalMonth: 4,
    debitAccount: 'TRAVEL',
    debitAmount: 21130,
    creditAccount: 'BANK',
    creditAmount: 21130,
    counterparty: 'JR東日本',
    description: 'Suica定期券（新宿〜渋谷）3ヶ月分',
    taxType: 'standard10',
    taxAmount: 1921,
    taxIncluded: true,
    isQualifiedInvoice: false,
    sourceType: 'credit_card',
    status: 'confirmed',
    createdAt: ts('2025-04-05'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-04-05'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j008',
    entryNumber: 8,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-04-15'),
    fiscalYear: 2025,
    fiscalMonth: 4,
    debitAccount: 'ADVERTISING',
    debitAmount: 5500,
    creditAccount: 'BANK',
    creditAmount: 5500,
    counterparty: 'ラクスルショップ',
    description: '名刺印刷 100枚',
    taxType: 'standard10',
    taxAmount: 500,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'confirmed',
    createdAt: ts('2025-04-20'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-04-20'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 5月 ──────────────────────────────────────────
  {
    id: 'j009',
    entryNumber: 9,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-05-30'),
    fiscalYear: 2025,
    fiscalMonth: 5,
    debitAccount: 'BANK',
    debitAmount: 330000,
    creditAccount: 'SALES',
    creditAmount: 330000,
    counterparty: '合同会社デジタルワークス',
    description: 'ECサイトリニューアル フロントエンド実装',
    taxType: 'standard10',
    taxAmount: 30000,
    taxIncluded: true,
    isQualifiedInvoice: true,
    invoiceRegistrationNumber: 'T2222222222222',
    sourceType: 'invoice',
    status: 'confirmed',
    createdAt: ts('2025-06-01'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-06-01'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j010',
    entryNumber: 10,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-05-15'),
    fiscalYear: 2025,
    fiscalMonth: 5,
    debitAccount: 'COMMUNICATION',
    debitAmount: 5500,
    creditAccount: 'BANK',
    creditAmount: 5500,
    counterparty: 'NTT東日本',
    description: 'フレッツ光 5月分インターネット料金',
    taxType: 'standard10',
    taxAmount: 500,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'bank',
    status: 'confirmed',
    createdAt: ts('2025-05-20'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-05-20'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 6月 ──────────────────────────────────────────
  {
    id: 'j011',
    entryNumber: 11,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-06-01'),
    fiscalYear: 2025,
    fiscalMonth: 6,
    debitAccount: 'INSURANCE',
    debitAmount: 35000,
    creditAccount: 'BANK',
    creditAmount: 35000,
    counterparty: '東京海上日動',
    description: '賠償責任保険 年間保険料',
    taxType: 'non_taxable',
    taxAmount: 0,
    taxIncluded: false,
    isQualifiedInvoice: false,
    sourceType: 'bank',
    status: 'confirmed',
    createdAt: ts('2025-06-05'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-06-05'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j012',
    entryNumber: 12,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-06-20'),
    fiscalYear: 2025,
    fiscalMonth: 6,
    debitAccount: 'SUPPLIES',
    debitAmount: 8800,
    creditAccount: 'BANK',
    creditAmount: 8800,
    counterparty: 'GitHub',
    description: 'GitHub Copilot Business 年間プラン',
    taxType: 'standard10',
    taxAmount: 800,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'confirmed',
    createdAt: ts('2025-06-25'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-06-25'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 7月 ──────────────────────────────────────────
  {
    id: 'j013',
    entryNumber: 13,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-07-25'),
    fiscalYear: 2025,
    fiscalMonth: 7,
    debitAccount: 'BANK',
    debitAmount: 440000,
    creditAccount: 'SALES',
    creditAmount: 440000,
    counterparty: '株式会社クリエイティブラボ',
    description: 'LP制作・CMSカスタマイズ 完成納品',
    taxType: 'standard10',
    taxAmount: 40000,
    taxIncluded: true,
    isQualifiedInvoice: true,
    invoiceRegistrationNumber: 'T3333333333333',
    sourceType: 'invoice',
    status: 'confirmed',
    createdAt: ts('2025-07-30'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-07-30'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j014',
    entryNumber: 14,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-07-10'),
    fiscalYear: 2025,
    fiscalMonth: 7,
    debitAccount: 'RENT',
    debitAmount: 33000,
    creditAccount: 'BANK',
    creditAmount: 33000,
    counterparty: 'TKP渋谷会議室',
    description: 'コワーキングスペース月額利用料 7月分',
    taxType: 'standard10',
    taxAmount: 3000,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'confirmed',
    createdAt: ts('2025-07-15'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-07-15'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 8月 ──────────────────────────────────────────
  {
    id: 'j015',
    entryNumber: 15,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-08-10'),
    fiscalYear: 2025,
    fiscalMonth: 8,
    debitAccount: 'SUPPLIES',
    debitAmount: 22000,
    creditAccount: 'BANK',
    creditAmount: 22000,
    counterparty: 'オカムラ',
    description: 'オフィスチェア（コンテッサ）購入',
    taxType: 'standard10',
    taxAmount: 2000,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'pending',
    createdAt: ts('2025-08-15'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-08-15'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 9月 ──────────────────────────────────────────
  {
    id: 'j016',
    entryNumber: 16,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-09-30'),
    fiscalYear: 2025,
    fiscalMonth: 9,
    debitAccount: 'BANK',
    debitAmount: 550000,
    creditAccount: 'SALES',
    creditAmount: 550000,
    counterparty: '株式会社フィンテック',
    description: '決済システムAPI連携 開発業務委託',
    taxType: 'standard10',
    taxAmount: 50000,
    taxIncluded: true,
    isQualifiedInvoice: true,
    invoiceRegistrationNumber: 'T4444444444444',
    sourceType: 'invoice',
    status: 'confirmed',
    createdAt: ts('2025-10-01'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-10-01'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j017',
    entryNumber: 17,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-09-10'),
    fiscalYear: 2025,
    fiscalMonth: 9,
    debitAccount: 'TAXES_AND_DUES',
    debitAmount: 50000,
    creditAccount: 'BANK',
    creditAmount: 50000,
    counterparty: '渋谷税務署',
    description: '予定納税（所得税） 第2期分',
    taxType: 'non_taxable',
    taxAmount: 0,
    taxIncluded: false,
    isQualifiedInvoice: false,
    sourceType: 'bank',
    status: 'confirmed',
    createdAt: ts('2025-09-15'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-09-15'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 10月 ──────────────────────────────────────────
  {
    id: 'j018',
    entryNumber: 18,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-10-31'),
    fiscalYear: 2025,
    fiscalMonth: 10,
    debitAccount: 'BANK',
    debitAmount: 330000,
    creditAccount: 'SALES',
    creditAmount: 330000,
    counterparty: '有限会社マーケティングプロ',
    description: 'MAツール連携・データ分析ダッシュボード開発',
    taxType: 'standard10',
    taxAmount: 30000,
    taxIncluded: true,
    isQualifiedInvoice: true,
    invoiceRegistrationNumber: 'T5555555555555',
    sourceType: 'invoice',
    status: 'confirmed',
    createdAt: ts('2025-11-01'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-11-01'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j019',
    entryNumber: 19,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-10-15'),
    fiscalYear: 2025,
    fiscalMonth: 10,
    debitAccount: 'ENTERTAINMENT',
    debitAmount: 32780,
    creditAccount: 'BANK',
    creditAmount: 32780,
    counterparty: '焼肉叙々苑 渋谷店',
    description: '取引先との打ち合わせ会食（3名）',
    taxType: 'standard10',
    taxAmount: 2980,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'pending',
    createdAt: ts('2025-10-20'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-10-20'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 11月 ──────────────────────────────────────────
  {
    id: 'j020',
    entryNumber: 20,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-11-01'),
    fiscalYear: 2025,
    fiscalMonth: 11,
    debitAccount: 'SUPPLIES',
    debitAmount: 28600,
    creditAccount: 'BANK',
    creditAmount: 28600,
    counterparty: 'Figma',
    description: 'Figma Professional 年間プラン（デザインツール）',
    taxType: 'standard10',
    taxAmount: 2600,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'confirmed',
    createdAt: ts('2025-11-05'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-11-05'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2025 12月 ──────────────────────────────────────────
  {
    id: 'j021',
    entryNumber: 21,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-12-25'),
    fiscalYear: 2025,
    fiscalMonth: 12,
    debitAccount: 'BANK',
    debitAmount: 660000,
    creditAccount: 'SALES',
    creditAmount: 660000,
    counterparty: 'NEXUS株式会社',
    description: '自社サービス開発 バックエンドAPI実装（12月分）',
    taxType: 'standard10',
    taxAmount: 60000,
    taxIncluded: true,
    isQualifiedInvoice: true,
    invoiceRegistrationNumber: 'T6666666666666',
    sourceType: 'invoice',
    status: 'confirmed',
    createdAt: ts('2025-12-28'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-12-28'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j022',
    entryNumber: 22,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2025-12-20'),
    fiscalYear: 2025,
    fiscalMonth: 12,
    debitAccount: 'SUPPLIES',
    debitAmount: 19800,
    creditAccount: 'BANK',
    creditAmount: 19800,
    counterparty: 'Amazon.co.jp',
    description: '業務用消耗品・事務用品まとめ買い',
    taxType: 'standard10',
    taxAmount: 1800,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'pending',
    createdAt: ts('2025-12-22'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2025-12-22'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2026 1月 ──────────────────────────────────────────
  {
    id: 'j023',
    entryNumber: 23,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2026-01-31'),
    fiscalYear: 2026,
    fiscalMonth: 1,
    debitAccount: 'BANK',
    debitAmount: 440000,
    creditAccount: 'SALES',
    creditAmount: 440000,
    counterparty: 'NEXUS株式会社',
    description: '自社サービス開発 バックエンドAPI実装（1月分）',
    taxType: 'standard10',
    taxAmount: 40000,
    taxIncluded: true,
    isQualifiedInvoice: true,
    invoiceRegistrationNumber: 'T6666666666666',
    sourceType: 'invoice',
    status: 'confirmed',
    createdAt: ts('2026-02-01'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2026-02-01'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j024',
    entryNumber: 24,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2026-01-15'),
    fiscalYear: 2026,
    fiscalMonth: 1,
    debitAccount: 'ADVERTISING',
    debitAmount: 16500,
    creditAccount: 'BANK',
    creditAmount: 16500,
    counterparty: 'さくらインターネット',
    description: 'さくらインターネット クラウドVPS 年間更新',
    taxType: 'standard10',
    taxAmount: 1500,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'confirmed',
    createdAt: ts('2026-01-20'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2026-01-20'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2026 2月 ──────────────────────────────────────────
  {
    id: 'j025',
    entryNumber: 25,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2026-02-28'),
    fiscalYear: 2026,
    fiscalMonth: 2,
    debitAccount: 'SUBCONTRACTING',
    debitAmount: 165000,
    creditAccount: 'BANK',
    creditAmount: 165000,
    counterparty: '山田太郎（業務委託）',
    description: 'デザイン業務委託費 2月分',
    taxType: 'non_taxable',
    taxAmount: 0,
    taxIncluded: false,
    isQualifiedInvoice: false,
    sourceType: 'bank',
    status: 'confirmed',
    createdAt: ts('2026-03-01'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2026-03-01'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j026',
    entryNumber: 26,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2026-02-15'),
    fiscalYear: 2026,
    fiscalMonth: 2,
    debitAccount: 'COMMUNICATION',
    debitAmount: 8800,
    creditAccount: 'BANK',
    creditAmount: 8800,
    counterparty: 'NTTドコモ',
    description: 'NTTドコモ 2月分携帯電話料金',
    taxType: 'standard10',
    taxAmount: 800,
    taxIncluded: true,
    isQualifiedInvoice: true,
    invoiceRegistrationNumber: 'T1234567890123',
    sourceType: 'bank',
    status: 'confirmed',
    createdAt: ts('2026-02-20'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2026-02-20'),
    updatedBy: 'test-user-demo',
  },

  // ── FY2026 3月 ──────────────────────────────────────────
  {
    id: 'j027',
    entryNumber: 27,
    version: 2,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2026-03-20'),
    fiscalYear: 2026,
    fiscalMonth: 3,
    debitAccount: 'BANK',
    debitAmount: 550000,
    creditAccount: 'SALES',
    creditAmount: 550000,
    counterparty: '株式会社グローバルテック',
    description: '海外ECシステム要件定義・設計支援',
    taxType: 'export',
    taxAmount: 0,
    taxIncluded: false,
    isQualifiedInvoice: false,
    sourceType: 'invoice',
    status: 'confirmed',
    createdAt: ts('2026-03-22'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2026-03-22'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j028',
    entryNumber: 28,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2026-03-10'),
    fiscalYear: 2026,
    fiscalMonth: 3,
    debitAccount: 'TRAVEL',
    debitAmount: 28600,
    creditAccount: 'BANK',
    creditAmount: 28600,
    counterparty: 'JTBビジネストラベル',
    description: '大阪出張 新幹線・宿泊費（2泊3日）',
    taxType: 'standard10',
    taxAmount: 2600,
    taxIncluded: true,
    isQualifiedInvoice: true,
    sourceType: 'credit_card',
    status: 'pending',
    createdAt: ts('2026-03-15'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2026-03-15'),
    updatedBy: 'test-user-demo',
  },
  {
    id: 'j029',
    entryNumber: 29,
    version: 1,
    isCurrent: true,
    isDeleted: false,
    transactionDate: ts('2026-03-22'),
    fiscalYear: 2026,
    fiscalMonth: 3,
    debitAccount: 'MISC_EXPENSE',
    debitAmount: 3300,
    creditAccount: 'BANK',
    creditAmount: 3300,
    counterparty: '不明',
    description: '用途不明の引き落とし 確認が必要',
    taxType: 'standard10',
    taxAmount: 300,
    taxIncluded: true,
    isQualifiedInvoice: false,
    sourceType: 'bank',
    status: 'pending',
    createdAt: ts('2026-03-22'),
    createdBy: 'test-user-demo',
    updatedAt: ts('2026-03-22'),
    updatedBy: 'test-user-demo',
  },
];

// ============================================================
// 証憑ドキュメント
// ============================================================
export const MOCK_DOCUMENTS: Document[] = [
  {
    id: 'd001',
    fileName: 'invoice_nexus_202512.pdf',
    originalFileName: '請求書_NEXUS_2025年12月.pdf',
    storageUrl: '',
    fileType: 'application/pdf',
    fileSizeBytes: 145678,
    documentType: 'invoice',
    transactionDate: ts('2025-12-25'),
    counterparty: 'NEXUS株式会社',
    amount: 660000,
    invoiceRegistrationNumber: 'T6666666666666',
    isVerifiedInvoice: true,
    linkedJournalIds: ['j021'],
    uploadedAt: ts('2025-12-28'),
    uploadedBy: 'test-user-demo',
    isDeleted: false,
  },
  {
    id: 'd002',
    fileName: 'receipt_amazon_202512.jpg',
    originalFileName: 'Amazon領収書_20251220.jpg',
    storageUrl: '',
    fileType: 'image/jpeg',
    fileSizeBytes: 234567,
    documentType: 'receipt',
    transactionDate: ts('2025-12-20'),
    counterparty: 'Amazon.co.jp',
    amount: 19800,
    linkedJournalIds: ['j022'],
    uploadedAt: ts('2025-12-22'),
    uploadedBy: 'test-user-demo',
    isDeleted: false,
  },
  {
    id: 'd003',
    fileName: 'statement_bank_202501.pdf',
    originalFileName: '三菱UFJ_通帳コピー_2026年1月.pdf',
    storageUrl: '',
    fileType: 'application/pdf',
    fileSizeBytes: 87654,
    documentType: 'bank_statement',
    transactionDate: ts('2026-01-31'),
    counterparty: '三菱UFJ銀行',
    amount: undefined,
    linkedJournalIds: ['j023', 'j024'],
    uploadedAt: ts('2026-02-05'),
    uploadedBy: 'test-user-demo',
    isDeleted: false,
  },
];

// ============================================================
// 月次サマリ FY2025
// ============================================================
export const MOCK_MONTHLY_2025: MonthlySummary[] = [
  { year: 2025, month: 1,  revenue: 0,       expenses: 24200,   profit: -24200 },
  { year: 2025, month: 2,  revenue: 0,       expenses: 181500,  profit: -181500 },
  { year: 2025, month: 3,  revenue: 550000,  expenses: 4800,    profit: 545200 },
  { year: 2025, month: 4,  revenue: 0,       expenses: 26630,   profit: -26630 },
  { year: 2025, month: 5,  revenue: 330000,  expenses: 5500,    profit: 324500 },
  { year: 2025, month: 6,  revenue: 0,       expenses: 43800,   profit: -43800 },
  { year: 2025, month: 7,  revenue: 440000,  expenses: 33000,   profit: 407000 },
  { year: 2025, month: 8,  revenue: 0,       expenses: 22000,   profit: -22000 },
  { year: 2025, month: 9,  revenue: 550000,  expenses: 50000,   profit: 500000 },
  { year: 2025, month: 10, revenue: 330000,  expenses: 32780,   profit: 297220 },
  { year: 2025, month: 11, revenue: 0,       expenses: 28600,   profit: -28600 },
  { year: 2025, month: 12, revenue: 660000,  expenses: 19800,   profit: 640200 },
];

// ============================================================
// 月次サマリ FY2026
// ============================================================
export const MOCK_MONTHLY_2026: MonthlySummary[] = [
  { year: 2026, month: 1,  revenue: 440000,  expenses: 16500,   profit: 423500 },
  { year: 2026, month: 2,  revenue: 0,       expenses: 173800,  profit: -173800 },
  { year: 2026, month: 3,  revenue: 550000,  expenses: 31900,   profit: 518100 },
];

// ============================================================
// 損益計算書 FY2025
// ============================================================
export const MOCK_PL_2025: ProfitAndLoss = {
  fiscalYear: 2025,
  sales: 2860000,
  otherIncome: 0,
  beginningInventory: 0,
  purchases: 0,
  endingInventory: 0,
  costOfGoodsSold: 0,
  totalRevenue: 2860000,
  expenses: {
    CASH: 0,
    BANK: 0,
    ACCOUNTS_RECEIVABLE: 0,
    PREPAID_EXPENSE: 0,
    INVENTORY: 0,
    FIXED_ASSETS: 0,
    OWNER_DRAWS: 0,
    ACCOUNTS_PAYABLE: 0,
    ACCRUED_EXPENSES: 0,
    DEPOSITS_RECEIVED: 0,
    CONSUMPTION_TAX_PAYABLE: 0,
    OWNER_CONTRIBUTIONS: 0,
    CAPITAL: 0,
    SALES: 0,
    OTHER_INCOME: 0,
    TAXES_AND_DUES: 50000,
    FREIGHT: 0,
    UTILITIES: 0,
    TRAVEL: 21130,
    COMMUNICATION: 5500,
    ADVERTISING: 20900,
    ENTERTAINMENT: 32780,
    INSURANCE: 35000,
    REPAIRS: 0,
    SUPPLIES: 80100,   // 書籍 + Adobe + GitHub + Figma
    DEPRECIATION: 16500, // PC減価償却（簡易計算）
    WELFARE: 0,
    SALARIES: 0,
    SUBCONTRACTING: 0,
    INTEREST: 0,
    RENT: 33000,
    BAD_DEBT: 0,
    MISC_EXPENSE: 0,
    PURCHASES: 0,
    FAMILY_WAGES: 0,
  },
  totalExpenses: 294910,
  familyWages: 0,
  grossProfit: 2565090,
  blueFormDeduction: 650000,
  blueFormDeductionLabel: '65万円（複式簿記 + e-Tax）',
  netIncome: 1915090,
};

// ============================================================
// 損益計算書 FY2026（1〜3月途中）
// ============================================================
export const MOCK_PL_2026: ProfitAndLoss = {
  fiscalYear: 2026,
  sales: 990000,
  otherIncome: 0,
  beginningInventory: 0,
  purchases: 0,
  endingInventory: 0,
  costOfGoodsSold: 0,
  totalRevenue: 990000,
  expenses: {
    CASH: 0,
    BANK: 0,
    ACCOUNTS_RECEIVABLE: 0,
    PREPAID_EXPENSE: 0,
    INVENTORY: 0,
    FIXED_ASSETS: 0,
    OWNER_DRAWS: 0,
    ACCOUNTS_PAYABLE: 0,
    ACCRUED_EXPENSES: 0,
    DEPOSITS_RECEIVED: 0,
    CONSUMPTION_TAX_PAYABLE: 0,
    OWNER_CONTRIBUTIONS: 0,
    CAPITAL: 0,
    SALES: 0,
    OTHER_INCOME: 0,
    TAXES_AND_DUES: 0,
    FREIGHT: 0,
    UTILITIES: 0,
    TRAVEL: 28600,
    COMMUNICATION: 8800,
    ADVERTISING: 16500,
    ENTERTAINMENT: 0,
    INSURANCE: 0,
    REPAIRS: 0,
    SUPPLIES: 0,
    DEPRECIATION: 0,
    WELFARE: 0,
    SALARIES: 0,
    SUBCONTRACTING: 165000,
    INTEREST: 0,
    RENT: 0,
    BAD_DEBT: 0,
    MISC_EXPENSE: 3300,
    PURCHASES: 0,
    FAMILY_WAGES: 0,
  },
  totalExpenses: 222200,
  familyWages: 0,
  grossProfit: 767800,
  blueFormDeduction: 650000,
  blueFormDeductionLabel: '65万円（複式簿記 + e-Tax）',
  netIncome: 117800,
};

// ============================================================
// 貸借対照表 FY2025
// ============================================================
export const MOCK_BS_2025: BalanceSheet = {
  fiscalYear: 2025,
  asOfDate: new Date('2025-12-31'),
  assets: {
    current: {
      CASH: 150000,
      BANK: 2100000,
      ACCOUNTS_RECEIVABLE: 0,
      PREPAID_EXPENSE: 0,
      INVENTORY: 0,
    } as Record<string, number>,
    fixed: {
      FIXED_ASSETS: 148500, // 165000 - 16500（減価償却）
    } as Record<string, number>,
    owner: {
      OWNER_DRAWS: 1200000,
    } as Record<string, number>,
    totalAssets: 2398500,
  },
  liabilities: {
    items: {
      ACCOUNTS_PAYABLE: 0,
      ACCRUED_EXPENSES: 0,
      CONSUMPTION_TAX_PAYABLE: 231000,
    } as Record<string, number>,
    totalLiabilities: 231000,
  },
  equity: {
    items: {
      CAPITAL: 100000,
      OWNER_CONTRIBUTIONS: 0,
    } as Record<string, number>,
    totalEquity: 2167500,
  },
  totalLiabilitiesAndEquity: 2398500,
};

// ============================================================
// 貸借対照表 FY2026（3月時点）
// ============================================================
export const MOCK_BS_2026: BalanceSheet = {
  fiscalYear: 2026,
  asOfDate: new Date('2026-03-24'),
  assets: {
    current: {
      CASH: 150000,
      BANK: 2337800,
      ACCOUNTS_RECEIVABLE: 0,
      PREPAID_EXPENSE: 0,
      INVENTORY: 0,
    } as Record<string, number>,
    fixed: {
      FIXED_ASSETS: 132000,
    } as Record<string, number>,
    owner: {
      OWNER_DRAWS: 600000,
    } as Record<string, number>,
    totalAssets: 2619800,
  },
  liabilities: {
    items: {
      ACCOUNTS_PAYABLE: 0,
      ACCRUED_EXPENSES: 0,
      CONSUMPTION_TAX_PAYABLE: 90000,
    } as Record<string, number>,
    totalLiabilities: 90000,
  },
  equity: {
    items: {
      CAPITAL: 100000,
      OWNER_CONTRIBUTIONS: 0,
    } as Record<string, number>,
    totalEquity: 2529800,
  },
  totalLiabilitiesAndEquity: 2619800,
};
