import { Timestamp } from 'firebase/firestore';
import type { Customer, Project, IssuedDocument } from '@/types';

function ts(dateStr: string): Timestamp {
  return Timestamp.fromDate(new Date(dateStr));
}

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    name: '株式会社サンプル商事',
    nameKana: 'カブシキガイシャサンプルショウジ',
    address: '東京都千代田区丸の内1-1-1',
    email: 'billing@sample-shoji.example.com',
    phone: '03-1234-5678',
    invoiceRegistrationNumber: 'T1234567890123',
    note: '月末締め翌月末払い',
    isDeleted: false,
    createdAt: ts('2025-01-10'),
    updatedAt: ts('2025-01-10'),
  },
  {
    id: 'cust-002',
    name: '合同会社テックラボ',
    nameKana: 'ゴウドウガイシャテックラボ',
    address: '大阪府大阪市北区梅田2-2-2',
    email: 'ap@techlab.example.com',
    phone: '06-9876-5432',
    invoiceRegistrationNumber: '',
    note: '',
    isDeleted: false,
    createdAt: ts('2025-02-01'),
    updatedAt: ts('2025-02-01'),
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    name: 'Webサイトリニューアル',
    customerId: 'cust-001',
    customerName: '株式会社サンプル商事',
    description: 'コーポレートサイトのデザイン刷新とCMS導入',
    status: 'active',
    startDate: '2025-04-01',
    endDate: '2025-09-30',
    isDeleted: false,
    createdAt: ts('2025-03-15'),
    updatedAt: ts('2025-08-01'),
  },
  {
    id: 'proj-002',
    name: '業務システム保守',
    customerId: 'cust-002',
    customerName: '合同会社テックラボ',
    description: '月次保守・問い合わせ対応',
    status: 'active',
    startDate: '2025-01-01',
    endDate: '',
    isDeleted: false,
    createdAt: ts('2025-01-05'),
    updatedAt: ts('2025-07-01'),
  },
  {
    id: 'proj-003',
    name: 'ロゴデザイン制作',
    customerId: 'cust-001',
    customerName: '株式会社サンプル商事',
    description: 'ブランドロゴ一式',
    status: 'completed',
    startDate: '2025-02-01',
    endDate: '2025-03-31',
    isDeleted: false,
    createdAt: ts('2025-01-20'),
    updatedAt: ts('2025-04-01'),
  },
];

export const MOCK_ISSUED_DOCUMENTS: IssuedDocument[] = [
  {
    id: 'iss-001',
    kind: 'estimate',
    documentNumber: 'EST-202504-0001',
    projectId: 'proj-001',
    projectName: 'Webサイトリニューアル',
    customerId: 'cust-001',
    customerName: '株式会社サンプル商事',
    customerAddress: '東京都千代田区丸の内1-1-1',
    issueDate: '2025-04-05',
    dueDate: '',
    title: 'Webサイトリニューアル見積',
    lineItems: [
      {
        id: 'li-1',
        description: 'デザイン制作',
        quantity: 1,
        unitPrice: 300000,
        taxType: 'standard10',
        priceMode: 'exclusive',
        withholding: false,
        amount: 300000,
      },
      {
        id: 'li-2',
        description: 'フロントエンド実装',
        quantity: 1,
        unitPrice: 450000,
        taxType: 'standard10',
        priceMode: 'exclusive',
        withholding: false,
        amount: 450000,
      },
      {
        id: 'li-3',
        description: 'CMS導入・設定',
        quantity: 1,
        unitPrice: 150000,
        taxType: 'standard10',
        priceMode: 'exclusive',
        withholding: false,
        amount: 150000,
      },
    ],
    subtotal: 900000,
    taxAmount: 90000,
    totalAmount: 990000,
    withholdingBase: 0,
    withholdingAmount: 0,
    amountDue: 990000,
    notes: '有効期限: 発行日より30日',
    status: 'issued',
    linkedJournalIds: [],
    postedToAccounting: false,
    isDeleted: false,
    createdAt: ts('2025-04-05'),
    updatedAt: ts('2025-04-05'),
    createdBy: 'test-user-demo',
    updatedBy: 'test-user-demo',
  },
  {
    id: 'iss-002',
    kind: 'invoice',
    documentNumber: 'INV-202506-0001',
    projectId: 'proj-001',
    projectName: 'Webサイトリニューアル',
    customerId: 'cust-001',
    customerName: '株式会社サンプル商事',
    customerAddress: '東京都千代田区丸の内1-1-1',
    issueDate: '2025-06-30',
    dueDate: '2025-07-31',
    title: '第1回請求（デザイン完了分）',
    lineItems: [
      {
        id: 'li-1',
        description: 'デザイン制作',
        quantity: 1,
        unitPrice: 300000,
        taxType: 'standard10',
        priceMode: 'exclusive',
        withholding: false,
        amount: 300000,
      },
    ],
    subtotal: 300000,
    taxAmount: 30000,
    totalAmount: 330000,
    withholdingBase: 0,
    withholdingAmount: 0,
    amountDue: 330000,
    notes: 'お振込口座: みずほ銀行 丸の内支店 普通 1234567',
    status: 'sent',
    linkedJournalIds: [],
    postedToAccounting: false,
    sourceDocumentId: 'iss-001',
    isDeleted: false,
    createdAt: ts('2025-06-30'),
    updatedAt: ts('2025-06-30'),
    createdBy: 'test-user-demo',
    updatedBy: 'test-user-demo',
  },
  {
    id: 'iss-003',
    kind: 'invoice',
    documentNumber: 'INV-202507-0001',
    projectId: 'proj-002',
    projectName: '業務システム保守',
    customerId: 'cust-002',
    customerName: '合同会社テックラボ',
    customerAddress: '大阪府大阪市北区梅田2-2-2',
    issueDate: '2025-07-31',
    dueDate: '2025-08-31',
    title: '7月分保守費用',
    lineItems: [
      {
        id: 'li-1',
        description: '月次保守費',
        quantity: 1,
        unitPrice: 50000,
        taxType: 'standard10',
        priceMode: 'exclusive',
        withholding: false,
        amount: 50000,
      },
    ],
    subtotal: 50000,
    taxAmount: 5000,
    totalAmount: 55000,
    withholdingBase: 0,
    withholdingAmount: 0,
    amountDue: 55000,
    notes: '',
    status: 'paid',
    linkedJournalIds: ['j-mock-ar-001', 'j-mock-pay-001'],
    postedToAccounting: true,
    isDeleted: false,
    createdAt: ts('2025-07-31'),
    updatedAt: ts('2025-08-05'),
    createdBy: 'test-user-demo',
    updatedBy: 'test-user-demo',
  },
  {
    id: 'iss-004',
    kind: 'receipt',
    documentNumber: 'RCP-202508-0001',
    projectId: 'proj-002',
    projectName: '業務システム保守',
    customerId: 'cust-002',
    customerName: '合同会社テックラボ',
    customerAddress: '大阪府大阪市北区梅田2-2-2',
    issueDate: '2025-08-05',
    dueDate: '',
    title: '7月分保守費用 領収',
    lineItems: [
      {
        id: 'li-1',
        description: '月次保守費',
        quantity: 1,
        unitPrice: 50000,
        taxType: 'standard10',
        priceMode: 'exclusive',
        withholding: false,
        amount: 50000,
      },
    ],
    subtotal: 50000,
    taxAmount: 5000,
    totalAmount: 55000,
    withholdingBase: 0,
    withholdingAmount: 0,
    amountDue: 55000,
    notes: '上記正に領収いたしました',
    status: 'issued',
    linkedJournalIds: ['j-mock-pay-001'],
    postedToAccounting: true,
    sourceDocumentId: 'iss-003',
    isDeleted: false,
    createdAt: ts('2025-08-05'),
    updatedAt: ts('2025-08-05'),
    createdBy: 'test-user-demo',
    updatedBy: 'test-user-demo',
  },
  {
    id: 'iss-005',
    kind: 'invoice',
    documentNumber: 'INV-202508-0001',
    projectId: 'proj-002',
    projectName: '業務システム保守',
    customerId: 'cust-002',
    customerName: '合同会社テックラボ',
    customerAddress: '大阪府大阪市北区梅田2-2-2',
    issueDate: '2025-08-20',
    dueDate: '2025-09-30',
    title: '業務委託費（源泉あり）',
    lineItems: [
      {
        id: 'li-1',
        description: '開発業務委託',
        quantity: 1,
        unitPrice: 110000,
        taxType: 'standard10',
        priceMode: 'inclusive',
        withholding: true,
        amount: 110000,
      },
    ],
    subtotal: 100000,
    taxAmount: 10000,
    totalAmount: 110000,
    withholdingBase: 100000,
    withholdingAmount: 10210,
    amountDue: 99790,
    notes: '源泉所得税（復興特別所得税含む 10.21%）を控除しています。',
    status: 'draft',
    linkedJournalIds: [],
    postedToAccounting: false,
    isDeleted: false,
    createdAt: ts('2025-08-20'),
    updatedAt: ts('2025-08-20'),
    createdBy: 'test-user-demo',
    updatedBy: 'test-user-demo',
  },
];
